# ### commands auto generated by Alembic - please adjust! ###
# revision identifiers, used by Alembic.
revision = 'fc2020131868' # <-- The ID from the filename
down_revision = '4bc938d9671c' # <-- The ID of the PREVIOUS migration script (check your versions folder for the exact ID)
branch_labels = None
depends_on = None
# ### end Alembic commands ###

def upgrade() -> None:
    # ... rest of the upgrade function ...

def downgrade() -> None:
    # ... rest of the downgrade function ...